import type { Metadata } from "next";
import { Inter , Poppins} from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";
import Provider from "@/components/Provider";
import { Toaster } from 'sonner'
import { TooltipProvider } from "@/components/ui/tooltip";
 
const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Toaster />
          <TooltipProvider>
        <div className="flex flex-col gap-1 md:flex-row md:gap-2">
          {/* <SideNavbar /> */}
          <div className="  w-full h-full">{children}</div>
        </div>
        </TooltipProvider>
        </Provider>
      </body>
    </html>
  );
}
